config/routes.rb
Sliders::Application.routes.draw do

  devise_for :users

  root 'home#index'
  resources :projects, only: [:index, :create, :update, :show, :destroy]
  resources :priorities

  namespace :admin do
    resources :users, only: [:index, :create, :update, :destroy]
    resources :projects, only: [:index]
  end
end

app/models/priority.rb
class Priority
  include Mongoid::Document
  field :name, type: String
  field :value, type: Float, default: 5
  field :description, type: String
  field :obligatory, type: Boolean, default: false

  belongs_to :project

  validates_presence_of :name, :project, :value
  validates_uniqueness_of :name, scope: :project_id
  validate :value_range

  private

  def value_range
    errors.add(:value, "out of range") unless value.in? (0..10)
  end
end

app/models/project.rb
class Project
  include Mongoid::Document
  field :title

  has_and_belongs_to_many :users
  has_many :priorities

  validates :title, uniqueness: true, presence: true

  after_create :add_default_priorities

  private

  def add_default_priorities
    priorities.create(name: 'Scope', obligatory: true, description: 'Feature completeness')
    priorities.create(name: 'Budget', obligatory: true, description: 'Stay within budget')
    priorities.create(name: 'Time', obligatory: true, description: 'Deliver project on time')
    priorities.create(name: 'Quality', obligatory: true, description: 'High quality, low defects')
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  field :admin, type: Boolean, default: false

  has_and_belongs_to_many :projects
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :require_admin!

  def require_admin!
    return false unless admin?
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::AdminController
  def index
    @projects = Project.all
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  def index
    @users = User.all
    @user = User.new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  helper_method :current_project
  def current_project
    Project.find(session[:project_id])
  end

  helper_method :admin?
  def admin?
    current_user.try(:admin)
  end

  def after_sign_in_path_for(resource)
    projects_path
  end

  def default_serializer_options
    {root: false}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  end
end

app/controllers/priorities_controller.rb
class PrioritiesController < ApplicationController
  before_action :set_priority, only: [:update, :show, :destroy]
  respond_to :json

  def create
    @priority = current_project.priorities.new(priority_params)
    if @priority.save
      render json: @priority
    else
      render text: "error: #{@priority.errors.full_messages}", status: 400
    end
  end

  def update
    if @priority.update_attributes(priority_params)
      render json: @priority
    else
      render text: "error: #{@priority.errors.full_messages}", status: 400
    end
  end

  def index
    @priorities = current_project.priorities
    respond_with @priorities
  end

  def show
    render json: @priority
  end

  def destroy
    if @priority.destroy()
      render({destroyed: true}.to_json)
    else
      render text: "error: #{@priority.errors.full_messages}", status: 400
    end
  end

  private

  def priority_params
    params.require(:priority).permit(:name, :value)
  end

  def set_priority
    @priority = current_project.priorities.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :show, :update, :destroy]

  def index
    @user = current_user
    @projects = @user.projects
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def show
    render text: "", status: 400 unless params[:id]
    session[:project_id] = params[:id]
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      @project.users << current_user
      redirect_to project_path(@project), notice: "Project created :)"
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to project_path(@project), notice: "Project updated :)"
    else
      render :edit
    end
  end

  def destroy
    if @project.destroy
      redirect_to projects_path, notice: "Project deleted"
    else
      redirect_to projects_path, notice: "Couldn't delete the project."
    end
  end

  def optimize
    optimizer = Optimizer.new(self)
    optimizer.optimize!
    render json: optimizer
  end

  private
  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller_js_include_tag
    javascript_include_tag controller_name if File.exists?("#{Rails.root}/app/assets/javascripts/#{controller_name}.coffee")
  end

  def action_js_include_tag
    js_file = "#{controller_name}-#{action_name}"
    javascript_include_tag js_file if File.exists?("#{Rails.root}/app/assets/javascripts/#{js_file}.coffee")
  end

  def controller_css_include_tag
    stylesheet_link_tag controller_name if Dir.glob("#{Rails.root}/app/assets/stylesheets/#{controller_name}.*css*").one?
  end

  def action_css_include_tag
    css_file = "#{controller_name}-#{action_name}"
    stylesheet_link_tag css_file if Dir.glob("#{Rails.root}/app/assets/stylesheets/#{css_file}.*css*").one?
  end
end

app/views/admin/projects/_project.html.haml
%tr
  %td= project.title
  %td= project.users.count

app/views/admin/projects/index.html.haml
%h2 Project

%table.table.table-striped
  %thead
    %th Name
    %th #Users
  %tbody
    - @projects.each do |project|
      = render 'admin/projects/project', project: project

app/views/admin/users/_user.html.haml
%tr
  %td= user.email
  %td= user.admin

app/views/admin/users/index.html.haml
%h1 Project settings

%h2 Users

%table.table.table-striped
  %thead
    %th Email
    %th Admin?
  %tbody
    - @users.each do |user|
      = render 'admin/users/user', user: user

= form_for [:admin, @user] do |f|
  = f.text_field :email
  = f.submit "Add client to project"

app/views/home/index.html.haml
.col-md-2
  %p.up-margin= link_to 'Log in!', new_user_session_path, class: 'btn btn-primary btn-large'

.col-md-8
  %h1.text-center SlideIt!

  %h2.text-center
    %em Tell me, what's important for you?

.col-md-2
  %p.up-margin= link_to "Sign up", new_user_registration_path, class: 'btn btn-large btn-primary'

#dziura

.row
  .col-md-4.col-md-offset-4#priorities
    #sliders

app/views/layouts/application.html.haml
!!!HTML
%html
  %head
    %title Kickoff Sliders
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = javascript_include_tag "kinetic-v5.1.0.min.js"
    = csrf_meta_tags
    = yield :head
    = controller_js_include_tag
    = action_js_include_tag
    = controller_css_include_tag
    = action_css_include_tag

  %body{ data: { view: { controller: controller_name.classify, action: action_name.classify } }, class: controller_name }
    - if notice
      %p.alert.alert-success.alert-dismissible.fade.in
        %span= notice
        = render 'shared/close_button'
    - if alert
      %p.alert.alert-danger.alert-dismissible.fade.in
        %span= alert
        = render 'shared/close_button'

    - if current_user
      = render 'shared/navbar'

    .container
      = yield

app/views/projects/index.html.haml
%h1 My Projects
.row.existing-projects
  .col-md-12
    - @projects.each do |project|
      .btn-group
        = link_to project.title, project_path(project), class: 'btn btn-lg btn-success'
        = link_to "X", project_path(project), class: 'btn btn-lg btn-danger', method: :delete, data: { confirm: "Are you sure to delete project '#{project.title}'?" }

%br
.row.new-project
  .col-md-4
    = form_for(Project.new) do |f|
      .input-group
        = f.text_field :title, class: 'form-control'
        .input-group-btn
          = f.submit "Add new project", class: 'btn btn-primary'

app/views/projects/show.html.haml
.row
  .col-md-12
    .top-row
      %h3.text-center
        Set your priorites for
        %em= @project.title.capitalize

.row
  .col-md-4.col-md-offset-4#priorities
    #sliders
    .input-group#new-priority
      %input.form-control
      .input-group-btn
        = link_to 'Add new priority', '#', class: 'add btn btn-medium btn-primary'

app/views/shared/_close_button.haml
%button.close{type: "button", data: {dismiss: "alert"}}
  %span{aria: {hidden: true}} &times;
  %span.sr-only Close

app/views/shared/_navbar.haml
.navbar.navbar-default
  .container-fluid
    %ul.nav.navbar-nav.navbar-left
      %li= link_to 'Kickoff', '#', class: 'navbar-brand'
    %ul.nav.navbar-nav.navbar-right
      - if admin?
        %li.dropdown
          %a.dropdown-toggle{data: { toggle: 'dropdown' }, aria: { haspopup: true, expanded: false }, href: '#', role: 'button' }
            Admin
            %span.caret
          %ul.dropdown-menu
            %li= link_to 'Users', admin_users_path
            %li= link_to 'Projects', admin_projects_path
      %li= link_to 'My Projects', projects_path
      %li= link_to "Hello, #{current_user.email}", edit_user_registration_path
      %li= link_to 'Sign out', destroy_user_session_path, method: :delete